"""Preset molekul untuk demo cepat di frontend — 47 molekul dalam 8 kategori."""

EXAMPLE_MOLECULES = [
    # ── DRUGS (8) ──────────────────────────────────────────────────────────────
    {
        "name": "Aspirin",
        "smiles": "CC(=O)Oc1ccccc1C(=O)O",
        "description": "Analgesik & antiinflamasi non-steroid (NSAID) yang paling banyak digunakan di dunia.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Caffeine",
        "smiles": "Cn1cnc2c1c(=O)n(C)c(=O)n2C",
        "description": "Stimulan sistem saraf pusat yang terdapat pada kopi, teh, dan minuman energi.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Paracetamol",
        "smiles": "CC(=O)Nc1ccc(O)cc1",
        "description": "Analgesik & antipiretik (acetaminophen) — hepatotoksik pada overdosis.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Ibuprofen",
        "smiles": "CC(C)Cc1ccc(C(C)C(=O)O)cc1",
        "description": "NSAID untuk nyeri, demam, dan inflamasi.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Diphenhydramine",
        "smiles": "O(CCN(C)C)C(c1ccccc1)c2ccccc2",
        "description": "Antihistamin generasi pertama, sering digunakan sebagai obat tidur.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Metformin",
        "smiles": "CN(C)C(=N)NC(=N)N",
        "description": "Obat antidiabetes tipe 2 lini pertama, mekanisme kerja melalui inhibisi kompleks I mitokondria.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Amoxicillin",
        "smiles": "CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O",
        "description": "Antibiotik beta-laktam spektrum luas untuk infeksi bakteri.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },
    {
        "name": "Loratadine",
        "smiles": "CCOC(=O)N1CCC(=C2c3ccc(Cl)cc3CCc4ccncc24)CC1",
        "description": "Antihistamin generasi kedua (non-sedating) untuk alergi.",
        "category": "drugs",
        "tags": ["safe-dose"],
    },

    # ── HORMONES (5) ───────────────────────────────────────────────────────────
    {
        "name": "Estradiol",
        "smiles": "OC1=CC2=C(CCC3C2CCC4(C)C3CCC4O)C=C1",
        "description": "Hormon estrogen utama pada wanita, berperan dalam siklus reproduksi.",
        "category": "hormones",
        "tags": ["endocrine-disruptor"],
    },
    {
        "name": "Testosterone",
        "smiles": "CC12CCC3C(C1CCC2=O)CCC4=CC(=O)CCC34C",
        "description": "Hormon androgen utama pada pria, mengendalikan perkembangan seksual.",
        "category": "hormones",
        "tags": ["endocrine-disruptor"],
    },
    {
        "name": "Progesterone",
        "smiles": "CC(=O)C1CCC2C1(C)CCC3C2CC=C4CC(=O)CCC34C",
        "description": "Hormon progesteron, berperan dalam siklus menstruasi dan kehamilan.",
        "category": "hormones",
        "tags": ["endocrine-disruptor"],
    },
    {
        "name": "Cortisol",
        "smiles": "CC12CCC3C(C1CC(O)C2(O)C(=O)CO)CCC4=CC(=O)CCC34C",
        "description": "Hormon stres utama yang dihasilkan oleh kelenjar adrenal.",
        "category": "hormones",
        "tags": ["safe-dose"],
    },
    {
        "name": "Dexamethasone",
        "smiles": "CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)CO",
        "description": "Kortikosteroid sintetik kuat, digunakan sebagai anti-inflamasi.",
        "category": "hormones",
        "tags": ["safe-dose"],
    },

    # ── ENDOCRINE DISRUPTORS (6) ────────────────────────────────────────────────
    {
        "name": "Bisphenol A",
        "smiles": "CC(C)(c1ccc(O)cc1)c2ccc(O)cc2",
        "description": "Monomer plastik polisulfonat & epoksi resin — endocrine disruptor luas.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor", "controversial"],
    },
    {
        "name": "Diethylstilbestrol",
        "smiles": "CC/C(=C(\\CC)c1ccc(O)cc1)c2ccc(O)cc2",
        "description": "Estrogen sintetik yang dilarang — terbukti karsinogenik dan teratogenik.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor", "carcinogen"],
    },
    {
        "name": "Atrazine",
        "smiles": "CCNc1nc(Cl)nc(NC(C)C)n1",
        "description": "Herbisida yang paling banyak digunakan di AS — pengganggu endokrin yang kontroversial.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor", "controversial"],
    },
    {
        "name": "Vinclozolin",
        "smiles": "CC1(C)OC(=O)N(c2ccc(Cl)c(Cl)c2)C1=O",
        "description": "Fungisida anti-androgen — mengganggu reseptor androgen pada perkembangan janin.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor"],
    },
    {
        "name": "17α-Ethinylestradiol",
        "smiles": "C#CC1(O)CCC2C1(C)CCC3C2CC=C4CC(O)CCC34C",
        "description": "Estrogen sintetik dalam pil KB — ditemukan dalam air minum dan mencemari ekosistem.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor", "controversial"],
    },
    {
        "name": "Nonylphenol",
        "smiles": "OC1=CC=C(CCCCCCCCC)C=C1",
        "description": "Surfaktan — metabolit deterjen yang mengganggu hormon pada ikan dan amfibi.",
        "category": "endocrine_disruptors",
        "tags": ["endocrine-disruptor"],
    },

    # ── SOLVENTS (6) ──────────────────────────────────────────────────────────
    {
        "name": "Benzene",
        "smiles": "c1ccccc1",
        "description": "Pelarut industri — karsinogen kelas 1 IARC, menyebabkan leukemia.",
        "category": "solvents",
        "tags": ["carcinogen"],
    },
    {
        "name": "Toluene",
        "smiles": "Cc1ccccc1",
        "description": "Pelarut organik dalam cat dan tiner — neurotoksik pada paparan tinggi.",
        "category": "solvents",
        "tags": ["controversial"],
    },
    {
        "name": "p-Xylene",
        "smiles": "Cc1ccc(C)cc1",
        "description": "Pelarut aromatik dalam industri — iritan saluran pernapasan.",
        "category": "solvents",
        "tags": ["controversial"],
    },
    {
        "name": "Acetone",
        "smiles": "CC(C)=O",
        "description": "Pelarut polar sederhana — toksisitas relatif rendah pada manusia.",
        "category": "solvents",
        "tags": ["safe-dose"],
    },
    {
        "name": "Chloroform",
        "smiles": "ClC(Cl)Cl",
        "description": "Pelarut klorinasi — hepatotoksik, kemungkinan karsinogenik (IARC 2B).",
        "category": "solvents",
        "tags": ["carcinogen", "controversial"],
    },
    {
        "name": "Ethanol",
        "smiles": "CCO",
        "description": "Alkohol konsumsi & pelarut — toksik pada dosis tinggi, karsinogenik kronis.",
        "category": "solvents",
        "tags": ["safe-dose", "carcinogen"],
    },

    # ── PESTICIDES (6) ────────────────────────────────────────────────────────
    {
        "name": "DDT",
        "smiles": "Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)(Cl)Cl)cc1",
        "description": "Insektisida organoklorin yang dilarang — persisten di lingkungan dan rantai makanan.",
        "category": "pesticides",
        "tags": ["endocrine-disruptor", "carcinogen"],
    },
    {
        "name": "Chlorpyrifos",
        "smiles": "CCOP(=S)(OCC)Oc1nc(Cl)c(Cl)cc1Cl",
        "description": "Insektisida organofosfat — neurotoksik, terutama berbahaya bagi anak-anak.",
        "category": "pesticides",
        "tags": ["controversial"],
    },
    {
        "name": "Glyphosate",
        "smiles": "OC(=O)CNCP(=O)(O)O",
        "description": "Herbisida paling banyak digunakan di dunia (Roundup) — kontroversi karsinogenisitas.",
        "category": "pesticides",
        "tags": ["controversial"],
    },
    {
        "name": "Permethrin",
        "smiles": "CC1(C)C(C=CCl)C1C(=O)OCC(Cl)(Cl)c1ccccc1",
        "description": "Insektisida piretroid — toksik terhadap ikan dan kucing.",
        "category": "pesticides",
        "tags": ["controversial"],
    },
    {
        "name": "Rotenone",
        "smiles": "COc1ccc2c(c1OC)CC(C(=O)O2)c3coc4cc(OC)c(OC)cc4c3=O",
        "description": "Insektisida alami dari tanaman — inhibitor kompleks I mitokondria, terkait Parkinson.",
        "category": "pesticides",
        "tags": ["carcinogen"],
    },
    {
        "name": "Malathion",
        "smiles": "CCOC(=O)CC(SP(=S)(OC)OC)C(=O)OCC",
        "description": "Insektisida organofosfat dengan toksisitas relatif rendah pada mamalia.",
        "category": "pesticides",
        "tags": ["controversial"],
    },

    # ── FOOD ADDITIVES (6) ─────────────────────────────────────────────────────
    {
        "name": "Aspartame",
        "smiles": "COC(=O)C(Cc1ccccc1)NC(=O)C(N)CC(=O)O",
        "description": "Pemanis buatan 200× lebih manis dari gula — kontroversial tapi umumnya dianggap aman.",
        "category": "food_additives",
        "tags": ["safe-dose", "controversial"],
    },
    {
        "name": "Saccharin",
        "smiles": "O=C1NS(=O)(=O)c2ccccc21",
        "description": "Pemanis buatan tertua — sempat dianggap karsinogenik tapi kemudian direhabilitasi.",
        "category": "food_additives",
        "tags": ["safe-dose", "controversial"],
    },
    {
        "name": "BHA",
        "smiles": "CC(C)(C)c1cc(O)ccc1OC",
        "description": "Butylated Hydroxyanisole — antioksidan pengawet makanan, kemungkinan karsinogenik.",
        "category": "food_additives",
        "tags": ["controversial", "carcinogen"],
    },
    {
        "name": "BHT",
        "smiles": "CC(C)(C)c1cc(C(C)(C)C)c(O)c(C(C)(C)C)c1",
        "description": "Butylated Hydroxytoluene — antioksidan pengawet makanan, endocrine disruptor lemah.",
        "category": "food_additives",
        "tags": ["controversial", "endocrine-disruptor"],
    },
    {
        "name": "Sodium Benzoate",
        "smiles": "OC(=O)c1ccccc1",
        "description": "Pengawet makanan yang umum — membentuk benzene karsinogenik dengan vitamin C.",
        "category": "food_additives",
        "tags": ["safe-dose", "controversial"],
    },
    {
        "name": "Tartrazine",
        "smiles": "Cc1ccc(N=Nc2cc(C(=O)[O-])cc(C(=O)[O-])c2O)c([N+](=O)[O-])c1S(=O)(=O)[O-]",
        "description": "Pewarna makanan kuning (E102) — alergen potensial, dilarang di beberapa negara.",
        "category": "food_additives",
        "tags": ["controversial"],
    },

    # ── CARCINOGENS (5) ───────────────────────────────────────────────────────
    {
        "name": "Benzo[a]pyrene",
        "smiles": "c1ccc2cc3cccc4ccc(c1)c2c34",
        "description": "Karsinogen PAH kelas 1 dari asap rokok dan makanan gosong — mutagen DNA kuat.",
        "category": "carcinogens",
        "tags": ["carcinogen"],
    },
    {
        "name": "Formaldehyde",
        "smiles": "C=O",
        "description": "Karsinogen kelas 1 IARC — terdapat dalam bahan bangunan, formalin, rokok.",
        "category": "carcinogens",
        "tags": ["carcinogen"],
    },
    {
        "name": "Acrylamide",
        "smiles": "NC(=O)C=C",
        "description": "Karsinogen yang terbentuk saat memasak makanan bertepung pada suhu tinggi (>120°C).",
        "category": "carcinogens",
        "tags": ["carcinogen"],
    },
    {
        "name": "Vinyl Chloride",
        "smiles": "ClC=C",
        "description": "Monomer PVC — karsinogen kelas 1 yang menyebabkan angiosarkoma hati.",
        "category": "carcinogens",
        "tags": ["carcinogen"],
    },
    {
        "name": "4-Aminobiphenyl",
        "smiles": "Nc1ccc(-c2ccccc2)cc1",
        "description": "Karsinogen aromatik amina — penyebab kanker kandung kemih pada pekerja industri.",
        "category": "carcinogens",
        "tags": ["carcinogen"],
    },

    # ── NATURAL COMPOUNDS (5) ──────────────────────────────────────────────────
    {
        "name": "Resveratrol",
        "smiles": "OC1=CC(=CC(=C1)/C=C/c2cc(O)ccc2O)O",
        "description": "Polifenol dalam anggur merah — aktivitas antioksidan dan anti-kanker in vitro.",
        "category": "natural",
        "tags": ["safe-dose"],
    },
    {
        "name": "Quercetin",
        "smiles": "O=c1c(OC)c(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12",
        "description": "Flavonoid antioksidan dalam bawang & apel — aktivitas anti-inflamasi.",
        "category": "natural",
        "tags": ["safe-dose"],
    },
    {
        "name": "Curcumin",
        "smiles": "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(OC)c2)ccc1O",
        "description": "Senyawa aktif kunyit — anti-inflamasi kuat, sedang diteliti sebagai agen antikanker.",
        "category": "natural",
        "tags": ["safe-dose"],
    },
    {
        "name": "Limonene",
        "smiles": "CC(=C)C1CCC(C)=CC1",
        "description": "Terpen dalam kulit jeruk — digunakan sebagai pewangi dan pelarut bio.",
        "category": "natural",
        "tags": ["safe-dose"],
    },
    {
        "name": "Capsaicin",
        "smiles": "COc1cc(CNC(=O)CCCC/C=C/CC(C)C)ccc1O",
        "description": "Senyawa pedas dalam cabai — analgesik topikal, aktivitas anti-tumor in vitro.",
        "category": "natural",
        "tags": ["safe-dose"],
    },
]
